from django.urls import path, re_path
from .views import*
from .edoofun_views import*

urlpatterns = [
    path('role_list_create', RoleListCreate.as_view(), name='RoleListCreate'),
    path('role_retrive_update_delete/<int:pk>', RoleRetriveUpdateDestroy.as_view(),
         name='RoleRetriveUpdateDestroy'),
    path('user-type_retrive_update_delete/<int:pk>',
         UserTypeRetriveUpdateDelete.as_view(), name='user-type-retrive-update-delete'),

    path('user-type_list_create', UserTypeListCreate.as_view(),
         name='UserTypeListCreate'),
    path('reporting_to_list_create', ReportingToListCreate.as_view(),
         name='ReportingToListCreate'),
    path('reporting_to_retrive_update_delete/<int:pk>', ReportingToRetriveUpdateDestroy.as_view(),
         name='ReportingToRetriveUpdateDestroy'),
    path('user_register', UserRegister.as_view(), name='UserRegister'),
    path('user_list', UserList.as_view(), name='UserList'),
    path('user_retrive_update_delete/<int:pk>', UserRetriveUpdateDelete.as_view(),
         name='UserRetriveUpdateDelete'),
    re_path('email-confirm-verify/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)', EmailConfirmVerify.as_view(),
            name='EmailConfirmVerify'),
    path('login', UserLogin.as_view(), name='UserLogin'),
    path('forget_password', ForgetPassword.as_view(), name='ForgetPassword'),
    path('change_password', ChangePassword.as_view(), name='ChangePassword'),
    re_path('reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)', ResetPasswordConfirm.as_view(),
            name='ResetPasswordConfirm'),
    re_path('reset_password/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)',
            ResetPassword.as_view(), name='ResetPassword'),
    path('logged-in-user-detail', LoggedIn.as_view(), name='LoggedIn'),
    path('logged-in-user-detail_mob', LoggedInMob.as_view(), name='LoggedIn'),
    path('add_user', AddUser.as_view(), name='AddUser'),
    path('update_user/<int:pk>', UpdateUser.as_view(), name='UpdateUser'),

    path('user_activate_deactivate/<int:pk>',
         UserActivateDeactivate.as_view(), name='UserActivate Deactivate'),
    path('generate_otp', GenerateOTP.as_view(), name='GenerateOTP'),
    path('otp_verification', OTPVerification.as_view(), name='OTPVerification'),
    path('add_role_of_user_list_create',
         AddRoleOfUserListCreate.as_view(), name='AddRoleOfUserListCreate'),
    path('reporting_to_list_by_user_detail/<int:pk>', ReportingToListByUserDetailList.as_view(),
         name='ReportingToListByUserDetailList'),
    path('update_reporting_to_list_by_user_detail', UpdateReportingToListByUserDetail.as_view(),
         name='UpdateReportingToListByUserDetail'),
    path('school_list_by_user/<int:pk>', SchoolListsByUser.as_view(),
         name='SchoolListsByUser'),
    path('user_role_retrive_update_delete/<int:pk>', UserRoleRetriveUpdateDestroy.as_view(),
         name='UserRoleRetriveUpdateDestroy'),
    path('user_list_by_school/<int:pk>',
         UserListBySchoolID.as_view(), name='User List By School'),
    path('get_roles_by_loggedin_user_id/<int:pk>',
         getRolesByLoggedinUserId.as_view(), name='Get Roles by Login ID'),
    path('get_roles_by_type',
         GetRoleByType.as_view(), name='GetRoleByType'),
    path('get_reporting_to_based_on_selected_role',
         GetReportingToBasedOnSelectedRole.as_view(), name='Get ReportingTo Based On SelectedRole'),
    path('account_list_create',
         AccountListCreate.as_view(), name='Account List Create'),
    path('update_account/<int:pk>',
         UpdateAccount.as_view(), name='Update Account'),


    path('license_list_by_logged_in_user_id/<int:pk>',
         LicenseListByLoggedInUser.as_view(), name='License List By Logged In User'),
    path('kreedo_roles_list',
         kreedoroleslist.as_view(), name='kreedo roles list'),
    path('kreedo_user_list',
         KreedoUserList.as_view(), name='kreedo user list'),

    path('get_credentials', KeyAccessOfS3.as_view(), name='KeyAccessOfS3'),


    path('bulk-upload/add-account', AddAccount.as_view(), name='Add Account'),
    path('bulk-upload/add-school', AddSchool.as_view(), name='Add School'),
    path('bulk-upload/add-school-grade-subject',
         AddSchoolGradeSubject.as_view(), name='Add School Grade Subject'),
    path('bulk-upload/add-user', AddUserData.as_view(), name='AddUserData'),

    path('edoofun/register_user',
         RegisterParent.as_view(), name='Register Parent'),
    path('edoofun/login_user_by_email_id',
         LoginUserBasedOnEmailD.as_view(), name='Login User Based On EmailD'),
    path('edoofun/login_user_based_on_contact_number',
         LoginUserBasedOnContactNumber.as_view(), name='Login User BasedOn Contact Number'),

    path('edoofun/get_all_account',
         GetAllAccounts.as_view(), name='Get All Accounts'),
    path('edoofun/get_users_based_on_school_id/<int:pk>',
         GetUsersBasedOnSchoolID.as_view(), name='Get User List Based on School Id'),
    path('edoofun/update_secret_pin_for_parent',
         UpdateSecretPinForParent.as_view(), name='Update Secret PIN For Parent'),
    path('edoofun/get_parent_details/<int:pk>',
         GetParentDetails.as_view(), name='Get Parent Details'),
    path('edoofun/logged_in_user_detail',
         LoggedInUser.as_view(), name='Logged In User'),
    path('edoofun/set_password', SetPassword.as_view(), name='Set Password'),
    path('edoofun/genrate_otp', EdoofunGenerateOTP.as_view(),
         name='Edoofun Generate OTP'),
    path('edoofun/otp_verify', EdoofunOTPVerification.as_view(),
         name='Edoofun OTP Verification'),
    path('edoofun/get_users_list', GetUserList.as_view(),
         name='Get User List'),
    path('edoofun/curriculum_dashboard_data', CurriculumDashboardData.as_view(),
         name='Curriculum Dashboard Data'),



]
